/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Bd.Conexao;
import Model.Consulta;
import Model.Paciente;
import Model.Dentista;
import Controller.ConsultaController;
import Model.Tabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author rafael
 */
public class CadastrarConsulta extends javax.swing.JFrame {
     Consulta consulta = new Consulta();
     ConsultaController consultaController = new ConsultaController();
     Dentista dentista = new Dentista();
     Paciente paciente = new Paciente();
     Conexao conexao = new Conexao();
     
    /** Creates new form cadastrarConsulta */
    public CadastrarConsulta() {
        initComponents();
        
        preencherTabela("SELECT ID, DENTISTA, PACIENTE, DATA_CONSULTA, HORA_INICIO, HORA_FIM FROM CONSULTAS ORDER BY DENTISTA");
        preencherTabelaRetorno("SELECT ID, DENTISTA, PACIENTE, DATA_CONSULTA, HORA_INICIO, HORA_FIM FROM CONSULTAS WHERE "
                + "TIPO_RETORNO = '2' ORDER BY DENTISTA");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCpf = new javax.swing.JTextField();
        jPaciente = new javax.swing.JTextField();
        jDentista = new javax.swing.JTextField();
        jData = new javax.swing.JTextField();
        jHoraFim = new javax.swing.JTextField();
        jHoraInicio = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bSalvar = new javax.swing.JButton();
        bBuscar4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultas = new javax.swing.JTable();
        jIdConsulta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConsultasRetorno = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Paciente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 100, -1, -1));

        jLabel2.setText("Dentista");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 132, -1, -1));

        jLabel3.setText("Hora Início");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 207, -1, -1));

        jLabel4.setText("Cadastrar Consulta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 34, -1, -1));

        jLabel5.setText("Hora Fim");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 242, -1, -1));

        jLabel6.setText("Data");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 166, -1, -1));

        jLabel7.setText("CPF");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 64, -1, -1));
        getContentPane().add(jCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 58, 133, -1));
        getContentPane().add(jPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 94, 133, -1));
        getContentPane().add(jDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 126, 133, -1));
        getContentPane().add(jData, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 160, 133, -1));
        getContentPane().add(jHoraFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 236, 133, -1));
        getContentPane().add(jHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 201, 133, -1));

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(bBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 57, -1, -1));

        bExcluir.setText("Excluir");
        bExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bExcluirMouseClicked(evt);
            }
        });
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(bExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 277, -1, -1));

        bEditar.setText("Editar");
        bEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditarMouseClicked(evt);
            }
        });
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });
        getContentPane().add(bEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 277, -1, -1));

        bSalvar.setText("Salvar");
        bSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalvarMouseClicked(evt);
            }
        });
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(bSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 277, -1, -1));

        bBuscar4.setText("Cadastrar");
        bBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscar4ActionPerformed(evt);
            }
        });
        getContentPane().add(bBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 277, -1, -1));

        jTableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 595, 138));
        getContentPane().add(jIdConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 43, -1, -1));

        jTableConsultasRetorno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsultasRetorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultasRetornoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableConsultasRetorno);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 595, 138));

        jLabel8.setText("Solicitações de retorno de consulta");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        jLabel9.setText("Consultas Cadastradas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bExcluirActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEditarActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSalvarActionPerformed

    private void bBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBuscar4ActionPerformed

    private void bSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalvarMouseClicked
        paciente.setId(Long.parseLong(jPaciente.getText()));
        dentista.setId(Long.parseLong(jDentista.getText()));
        consulta.setPaciente(paciente);
        consulta.setDentista(dentista);
        consulta.setData(jData.getText());
        consulta.setHoraInicio(jHoraInicio.getText());
        consulta.setHoraFim(jHoraFim.getText());
        consultaController.insereConsulta(consulta);
        //this.limpaCampos();
        //bSalvar.setEnabled(false);
        //jNome.setEnabled(false);
        //jTelefone.setEnabled(false);
        //bCadastrar.setEnabled(true);
        //preencherTabela("SELECT NOME, CPF, TELEFONE_FIXO, EMAIL FROM PACIENTES ORDER BY NOME");
        preencherTabela("SELECT ID, DENTISTA, PACIENTE, DATA_CONSULTA, HORA_INICIO, HORA_FIM FROM CONSULTAS ORDER BY DENTISTA");
        
    }//GEN-LAST:event_bSalvarMouseClicked

    private void bEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarMouseClicked
        paciente.setId(Long.parseLong(jPaciente.getText()));
        dentista.setId(Long.parseLong(jDentista.getText()));
        consulta.setId(Integer.parseInt(jIdConsulta.getText()));
        consulta.setPaciente(paciente);
        consulta.setDentista(dentista);
        consulta.setData(jData.getText());
        consulta.setHoraInicio(jHoraInicio.getText());
        consulta.setHoraFim(jHoraFim.getText());
        consultaController.editarConsulta(consulta);
        preencherTabela("SELECT ID, DENTISTA, PACIENTE, DATA_CONSULTA, HORA_INICIO, HORA_FIM FROM CONSULTAS ORDER BY DENTISTA");
    }//GEN-LAST:event_bEditarMouseClicked

    private void jTableConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultasMouseClicked
        String id = "" + jTableConsultas.getValueAt(jTableConsultas.getSelectedRow(), 0);
        conexao.conecta();
        conexao.executaSql("SELECT ID, DENTISTA, PACIENTE, DATA_CONSULTA, HORA_INICIO, HORA_FIM FROM CONSULTAS WHERE ID = "+id+"");
        try {
            conexao.rs.first();
            jIdConsulta.setText(""+conexao.rs.getInt("id"));
            jDentista.setText(conexao.rs.getString("dentista"));
            jPaciente.setText(String.valueOf(conexao.rs.getLong("paciente")));
            jData.setText(conexao.rs.getString("data_consulta"));
            jHoraInicio.setText(conexao.rs.getString("hora_inicio"));
            jHoraFim.setText(conexao.rs.getString("hora_fim"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Errocriado no mouse clicked: "+ex);
        }
        conexao.desconecta();
        /*bEditar.setEnabled(true);
        bSalvar.setEnabled(false);
        bExcluir.setEnabled(true);
        bEditar.setEnabled(true);
        bCadastrar.setEnabled(false);
        jNome.setEnabled(true);
        jTelefone.setEnabled(true);*/
    }//GEN-LAST:event_jTableConsultasMouseClicked

    private void bExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExcluirMouseClicked
        consulta.setId(Integer.parseInt(jIdConsulta.getText()));
        consultaController.excluiConsulta(consulta);
        preencherTabela("SELECT ID, DENTISTA, PACIENTE, DATA_CONSULTA, HORA_INICIO, HORA_FIM FROM CONSULTAS ORDER BY DENTISTA");
    }//GEN-LAST:event_bExcluirMouseClicked

    private void jTableConsultasRetornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultasRetornoMouseClicked
        String id = "" + jTableConsultasRetorno.getValueAt(jTableConsultasRetorno.getSelectedRow(), 0);
        conexao.conecta();
        conexao.executaSql("SELECT ID, DENTISTA, PACIENTE, DATA_CONSULTA, HORA_INICIO, HORA_FIM FROM CONSULTAS WHERE ID = "+id+"");
        try {
            conexao.rs.first();
            //jIdConsulta.setText(""+conexao.rs.getInt("id"));
            jDentista.setText(conexao.rs.getString("dentista"));
            jPaciente.setText(String.valueOf(conexao.rs.getLong("paciente")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Errocriado no mouse clicked: "+ex);
        }
        conexao.desconecta();
        /*bEditar.setEnabled(true);
        bSalvar.setEnabled(false);
        bExcluir.setEnabled(true);
        bEditar.setEnabled(true);
        bCadastrar.setEnabled(false);
        jNome.setEnabled(true);
        jTelefone.setEnabled(true);*/
    }//GEN-LAST:event_jTableConsultasRetornoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarConsulta().setVisible(true);
            }
        });
    }
    
    /*public void limpaCampos(){
        jId.setText("");
        jCpf.setText("");
        jNome.setText("");
        jTelefone.setText("");
    }*/
    
    public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID","Dentista", "Paciente", "Data da Consulta", "Hora inicial", "Hora final"};
        conexao.conecta();
        conexao.executaSql(sql);
        
        try{
            conexao.rs.first();
        do{
            dados.add(new Object[]{conexao.rs.getInt("id") ,conexao.rs.getInt("dentista"), conexao.rs.getInt("paciente"),
                conexao.rs.getString("data_consulta"),
                conexao.rs.getString("hora_inicio"),
                conexao.rs.getString("hora_fim")});
        }while(conexao.rs.next());
        }catch(SQLException ex){
            //JOptionPane.showMessageDialog(rootPane,"erro ao preencher arraLyst: "+ ex);
        }
        Tabela modelo = new Tabela(dados, colunas);
        jTableConsultas.setModel(modelo);
        jTableConsultas.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableConsultas.getColumnModel().getColumn(0).setResizable(false);
        jTableConsultas.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableConsultas.getColumnModel().getColumn(1).setResizable(false);
        jTableConsultas.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableConsultas.getColumnModel().getColumn(2).setResizable(false);
        jTableConsultas.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableConsultas.getColumnModel().getColumn(3).setResizable(false);
        jTableConsultas.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableConsultas.getColumnModel().getColumn(4).setResizable(false);
        jTableConsultas.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTableConsultas.getColumnModel().getColumn(5).setResizable(false);
        jTableConsultas.getTableHeader().setReorderingAllowed(false);
        jTableConsultas.setAutoResizeMode(jTableConsultas.AUTO_RESIZE_OFF);
        jTableConsultas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
    
    public void preencherTabelaRetorno(String sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID","Dentista", "Paciente", "Data da Consulta", "Hora inicial", "Hora final"};
        conexao.conecta();
        conexao.executaSql(sql);
        
        try{
            conexao.rs.first();
        do{
            dados.add(new Object[]{conexao.rs.getInt("id") ,conexao.rs.getInt("dentista"), conexao.rs.getInt("paciente"),
                conexao.rs.getString("data_consulta"),
                conexao.rs.getString("hora_inicio"),
                conexao.rs.getString("hora_fim")});
        }while(conexao.rs.next());
        }catch(SQLException ex){
            //JOptionPane.showMessageDialog(rootPane,"erro ao preencher arraLyst: "+ ex);
        }
        Tabela modelo = new Tabela(dados, colunas);
        jTableConsultasRetorno.setModel(modelo);
        jTableConsultasRetorno.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableConsultasRetorno.getColumnModel().getColumn(0).setResizable(false);
        jTableConsultasRetorno.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableConsultasRetorno.getColumnModel().getColumn(1).setResizable(false);
        jTableConsultasRetorno.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableConsultasRetorno.getColumnModel().getColumn(2).setResizable(false);
        jTableConsultasRetorno.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableConsultasRetorno.getColumnModel().getColumn(3).setResizable(false);
        jTableConsultasRetorno.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableConsultasRetorno.getColumnModel().getColumn(4).setResizable(false);
        jTableConsultasRetorno.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTableConsultasRetorno.getColumnModel().getColumn(5).setResizable(false);
        jTableConsultasRetorno.getTableHeader().setReorderingAllowed(false);
        jTableConsultasRetorno.setAutoResizeMode(jTableConsultas.AUTO_RESIZE_OFF);
        jTableConsultasRetorno.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bBuscar4;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bSalvar;
    private javax.swing.JTextField jCpf;
    private javax.swing.JTextField jData;
    private javax.swing.JTextField jDentista;
    private javax.swing.JTextField jHoraFim;
    private javax.swing.JTextField jHoraInicio;
    private javax.swing.JTextField jIdConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableConsultas;
    private javax.swing.JTable jTableConsultasRetorno;
    // End of variables declaration//GEN-END:variables

}
