/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Bd.Conexao;
import Model.Consulta;
import Model.Dentista;
import Model.Paciente;
import Model.Tabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author rafael
 */
public class TelaPrincipalDentista extends javax.swing.JFrame {

    Conexao conexao = new Conexao();
    Consulta consulta = new Consulta();
    Paciente paciente = new Paciente();
    
    /**
     * Creates new form telaPrincipalDentista
     */
    public TelaPrincipalDentista(Dentista dentista) {
        initComponents();
        jNomeDentista.setText(dentista.getNome());
        JOptionPane.showMessageDialog(this, dentista.getCpf());
        preencherTabela("SELECT C.ID, C.PACIENTE, C.DATA_CONSULTA, C.HORA_INICIO, C.HORA_FIM FROM CONSULTAS C"
                + " INNER JOIN DENTISTAS D ON D.ID = C.DENTISTA WHERE D.CPF = "+ dentista.getCpf());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNomeDentista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultas = new javax.swing.JTable();
        jHoraFim = new javax.swing.JTextField();
        jIdConsulta = new javax.swing.JTextField();
        jHoraInicio = new javax.swing.JTextField();
        jData = new javax.swing.JTextField();
        jPaciente = new javax.swing.JTextField();
        bEditaConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dentista");

        jTableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultas);

        bEditaConsulta.setText("Editar informações consulta");
        bEditaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditaConsultaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jNomeDentista, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIdConsulta)
                            .addComponent(jPaciente)
                            .addComponent(jData)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHoraInicio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bEditaConsulta)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jHoraFim))))))))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jNomeDentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addComponent(jIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(bEditaConsulta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        setBounds(0, 0, 1026, 507);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultasMouseClicked
        String id = "" + jTableConsultas.getValueAt(jTableConsultas.getSelectedRow(), 0);
        conexao.conecta();
        conexao.executaSql("SELECT ID, PACIENTE, DATA_CONSULTA, HORA_INICIO, HORA_FIM FROM CONSULTAS WHERE ID = "+id+"");
        try {
            conexao.rs.first();
            jIdConsulta.setText(""+conexao.rs.getInt("id"));
            jPaciente.setText(String.valueOf(conexao.rs.getLong("paciente")));
            jData.setText(conexao.rs.getString("data_consulta"));
            jHoraInicio.setText(conexao.rs.getString("hora_inicio"));
            jHoraFim.setText(conexao.rs.getString("hora_fim"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Errocriado no mouse clicked: "+ex);
        }
        conexao.desconecta();
        /*bEditar.setEnabled(true);
        bSalvar.setEnabled(false);
        bExcluir.setEnabled(true);
        bEditar.setEnabled(true);
        bCadastrar.setEnabled(false);
        jNome.setEnabled(true);
        jTelefone.setEnabled(true);*/
    }//GEN-LAST:event_jTableConsultasMouseClicked

    private void bEditaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditaConsultaMouseClicked
        consulta.setId(Integer.parseInt(jIdConsulta.getText()));
        paciente.setId(Long.parseLong(jPaciente.getText()));
        consulta.setPaciente(paciente);
        TelaDentistaConsulta telaDentistaConsulta = new TelaDentistaConsulta(consulta);
        telaDentistaConsulta.setVisible(true);
    }//GEN-LAST:event_bEditaConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipalDentista().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipalDentista().setVisible(true);
            }
        });*/
    }                                         

    
    public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Paciente", "Data da Consulta", "Hora inicial", "Hora final"};
        conexao.conecta();
        conexao.executaSql(sql);
        
        try{
            conexao.rs.first();
        do{
            dados.add(new Object[]{conexao.rs.getInt("id") , conexao.rs.getInt("paciente"),
                conexao.rs.getString("data_consulta"),
                conexao.rs.getString("hora_inicio"),
                conexao.rs.getString("hora_fim")});
        }while(conexao.rs.next());
        }catch(SQLException ex){
            //JOptionPane.showMessageDialog(rootPane,"erro ao preencher arraLyst: "+ ex);
        }
        Tabela modelo = new Tabela(dados, colunas);
        jTableConsultas.setModel(modelo);
        jTableConsultas.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableConsultas.getColumnModel().getColumn(0).setResizable(false);
        jTableConsultas.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableConsultas.getColumnModel().getColumn(1).setResizable(false);
        jTableConsultas.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableConsultas.getColumnModel().getColumn(2).setResizable(false);
        jTableConsultas.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableConsultas.getColumnModel().getColumn(3).setResizable(false);
        jTableConsultas.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableConsultas.getColumnModel().getColumn(4).setResizable(false);
        jTableConsultas.getTableHeader().setReorderingAllowed(false);
        jTableConsultas.setAutoResizeMode(jTableConsultas.AUTO_RESIZE_OFF);
        jTableConsultas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEditaConsulta;
    private javax.swing.JTextField jData;
    private javax.swing.JTextField jHoraFim;
    private javax.swing.JTextField jHoraInicio;
    private javax.swing.JTextField jIdConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNomeDentista;
    private javax.swing.JTextField jPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultas;
    // End of variables declaration//GEN-END:variables
}
