/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author rafael
 */
public class telaDentistaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form telaDentistaConsulta
     */
    public telaDentistaConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDentes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSolicitar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        bSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPrognostico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDiagnostico = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jProcedimento = new javax.swing.JTextArea();
        j31 = new javax.swing.JCheckBox();
        j11 = new javax.swing.JCheckBox();
        j12 = new javax.swing.JCheckBox();
        j13 = new javax.swing.JCheckBox();
        j14 = new javax.swing.JCheckBox();
        j15 = new javax.swing.JCheckBox();
        j18 = new javax.swing.JCheckBox();
        j16 = new javax.swing.JCheckBox();
        j17 = new javax.swing.JCheckBox();
        j21 = new javax.swing.JCheckBox();
        j22 = new javax.swing.JCheckBox();
        j23 = new javax.swing.JCheckBox();
        j24 = new javax.swing.JCheckBox();
        j25 = new javax.swing.JCheckBox();
        j26 = new javax.swing.JCheckBox();
        j27 = new javax.swing.JCheckBox();
        j28 = new javax.swing.JCheckBox();
        j48 = new javax.swing.JCheckBox();
        j47 = new javax.swing.JCheckBox();
        j46 = new javax.swing.JCheckBox();
        j45 = new javax.swing.JCheckBox();
        j44 = new javax.swing.JCheckBox();
        j43 = new javax.swing.JCheckBox();
        j42 = new javax.swing.JCheckBox();
        j41 = new javax.swing.JCheckBox();
        j38 = new javax.swing.JCheckBox();
        j37 = new javax.swing.JCheckBox();
        j36 = new javax.swing.JCheckBox();
        j35 = new javax.swing.JCheckBox();
        j34 = new javax.swing.JCheckBox();
        j33 = new javax.swing.JCheckBox();
        j32 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Prognóstico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel2.setText("Diagnóstico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setText("Procedimento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jSolicitar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Retorno de Consulta", "Cirurgia" }));
        getContentPane().add(jSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, 30));

        jLabel4.setText("Solicitar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 20));

        bSalvar.setText("Salvar");
        bSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(bSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        jLabel5.setText("Informações da consulta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 27, -1, -1));

        jLabel7.setText("Paciente :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 64, -1, -1));

        jLabel6.setText("\"João Pedro\"");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 64, -1, -1));

        jPrognostico.setColumns(20);
        jPrognostico.setRows(5);
        jScrollPane1.setViewportView(jPrognostico);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 400, 80));

        jDiagnostico.setColumns(20);
        jDiagnostico.setRows(5);
        jScrollPane2.setViewportView(jDiagnostico);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 400, 80));

        jProcedimento.setColumns(20);
        jProcedimento.setRows(5);
        jScrollPane3.setViewportView(jProcedimento);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 400, 80));

        grupoDentes.add(j31);
        j31.setText("31");
        j31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j31ActionPerformed(evt);
            }
        });
        getContentPane().add(j31, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        grupoDentes.add(j11);
        j11.setText("11");
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j11ActionPerformed(evt);
            }
        });
        getContentPane().add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        grupoDentes.add(j12);
        j12.setText("12");
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j12ActionPerformed(evt);
            }
        });
        getContentPane().add(j12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, -1, -1));

        grupoDentes.add(j13);
        j13.setText("13");
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j13ActionPerformed(evt);
            }
        });
        getContentPane().add(j13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

        grupoDentes.add(j14);
        j14.setText("14");
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j14ActionPerformed(evt);
            }
        });
        getContentPane().add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        grupoDentes.add(j15);
        j15.setText("15");
        j15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j15ActionPerformed(evt);
            }
        });
        getContentPane().add(j15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        grupoDentes.add(j18);
        j18.setText("18");
        j18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j18ActionPerformed(evt);
            }
        });
        getContentPane().add(j18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        grupoDentes.add(j16);
        j16.setText("16");
        j16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j16ActionPerformed(evt);
            }
        });
        getContentPane().add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        grupoDentes.add(j17);
        j17.setText("17");
        j17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j17ActionPerformed(evt);
            }
        });
        getContentPane().add(j17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        grupoDentes.add(j21);
        j21.setText("21");
        j21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j21ActionPerformed(evt);
            }
        });
        getContentPane().add(j21, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));

        grupoDentes.add(j22);
        j22.setText("22");
        j22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j22ActionPerformed(evt);
            }
        });
        getContentPane().add(j22, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, -1, -1));

        grupoDentes.add(j23);
        j23.setText("23");
        j23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j23ActionPerformed(evt);
            }
        });
        getContentPane().add(j23, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, -1, -1));

        grupoDentes.add(j24);
        j24.setText("24");
        j24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j24ActionPerformed(evt);
            }
        });
        getContentPane().add(j24, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, -1, -1));

        grupoDentes.add(j25);
        j25.setText("25");
        j25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j25ActionPerformed(evt);
            }
        });
        getContentPane().add(j25, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, -1, -1));

        grupoDentes.add(j26);
        j26.setText("26");
        j26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j26ActionPerformed(evt);
            }
        });
        getContentPane().add(j26, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, -1, -1));

        grupoDentes.add(j27);
        j27.setText("27");
        j27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j27ActionPerformed(evt);
            }
        });
        getContentPane().add(j27, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, -1, -1));

        grupoDentes.add(j28);
        j28.setText("28");
        j28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j28ActionPerformed(evt);
            }
        });
        getContentPane().add(j28, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, -1, -1));

        grupoDentes.add(j48);
        j48.setText("48");
        j48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j48ActionPerformed(evt);
            }
        });
        getContentPane().add(j48, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        grupoDentes.add(j47);
        j47.setText("47");
        j47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j47ActionPerformed(evt);
            }
        });
        getContentPane().add(j47, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        grupoDentes.add(j46);
        j46.setText("46");
        j46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j46ActionPerformed(evt);
            }
        });
        getContentPane().add(j46, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        grupoDentes.add(j45);
        j45.setText("45");
        j45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j45ActionPerformed(evt);
            }
        });
        getContentPane().add(j45, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        grupoDentes.add(j44);
        j44.setText("44");
        j44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j44ActionPerformed(evt);
            }
        });
        getContentPane().add(j44, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, -1, -1));

        grupoDentes.add(j43);
        j43.setText("43");
        j43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j43ActionPerformed(evt);
            }
        });
        getContentPane().add(j43, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        grupoDentes.add(j42);
        j42.setText("42");
        j42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j42ActionPerformed(evt);
            }
        });
        getContentPane().add(j42, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        grupoDentes.add(j41);
        j41.setText("41");
        j41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j41ActionPerformed(evt);
            }
        });
        getContentPane().add(j41, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, -1, -1));

        grupoDentes.add(j38);
        j38.setText("38");
        j38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j38ActionPerformed(evt);
            }
        });
        getContentPane().add(j38, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, -1, -1));

        grupoDentes.add(j37);
        j37.setText("37");
        j37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j37ActionPerformed(evt);
            }
        });
        getContentPane().add(j37, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, -1, -1));

        grupoDentes.add(j36);
        j36.setText("36");
        j36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j36ActionPerformed(evt);
            }
        });
        getContentPane().add(j36, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, -1));

        grupoDentes.add(j35);
        j35.setText("35");
        j35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j35ActionPerformed(evt);
            }
        });
        getContentPane().add(j35, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, -1, -1));

        grupoDentes.add(j34);
        j34.setText("34");
        j34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j34ActionPerformed(evt);
            }
        });
        getContentPane().add(j34, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, -1, -1));

        grupoDentes.add(j33);
        j33.setText("33");
        j33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j33ActionPerformed(evt);
            }
        });
        getContentPane().add(j33, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, -1, -1));

        grupoDentes.add(j32);
        j32.setText("32");
        j32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j32ActionPerformed(evt);
            }
        });
        getContentPane().add(j32, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j31ActionPerformed

    private void j11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j11ActionPerformed

    private void j12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j12ActionPerformed

    private void j13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j13ActionPerformed

    private void j14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j14ActionPerformed

    private void j15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j15ActionPerformed

    private void j18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j18ActionPerformed

    private void j16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j16ActionPerformed

    private void j17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j17ActionPerformed

    private void j21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j21ActionPerformed

    private void j22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j22ActionPerformed

    private void j23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j23ActionPerformed

    private void j24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j24ActionPerformed

    private void j25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j25ActionPerformed

    private void j26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j26ActionPerformed

    private void j27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j27ActionPerformed

    private void j28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j28ActionPerformed

    private void j48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j48ActionPerformed

    private void j47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j47ActionPerformed

    private void j46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j46ActionPerformed

    private void j45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j45ActionPerformed

    private void j44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j44ActionPerformed

    private void j43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j43ActionPerformed

    private void j42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j42ActionPerformed

    private void j41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j41ActionPerformed

    private void j38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j38ActionPerformed

    private void j37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j37ActionPerformed

    private void j36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j36ActionPerformed

    private void j35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j35ActionPerformed

    private void j34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j34ActionPerformed

    private void j33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j33ActionPerformed

    private void j32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j32ActionPerformed

    private void bSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalvarMouseClicked
        JOptionPane.showMessageDialog(this, grupoDentes.getSelection().getActionCommand());
    }//GEN-LAST:event_bSalvarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaDentistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaDentistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaDentistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaDentistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaDentistaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSalvar;
    private javax.swing.ButtonGroup grupoDentes;
    private javax.swing.JCheckBox j11;
    private javax.swing.JCheckBox j12;
    private javax.swing.JCheckBox j13;
    private javax.swing.JCheckBox j14;
    private javax.swing.JCheckBox j15;
    private javax.swing.JCheckBox j16;
    private javax.swing.JCheckBox j17;
    private javax.swing.JCheckBox j18;
    private javax.swing.JCheckBox j21;
    private javax.swing.JCheckBox j22;
    private javax.swing.JCheckBox j23;
    private javax.swing.JCheckBox j24;
    private javax.swing.JCheckBox j25;
    private javax.swing.JCheckBox j26;
    private javax.swing.JCheckBox j27;
    private javax.swing.JCheckBox j28;
    private javax.swing.JCheckBox j31;
    private javax.swing.JCheckBox j32;
    private javax.swing.JCheckBox j33;
    private javax.swing.JCheckBox j34;
    private javax.swing.JCheckBox j35;
    private javax.swing.JCheckBox j36;
    private javax.swing.JCheckBox j37;
    private javax.swing.JCheckBox j38;
    private javax.swing.JCheckBox j41;
    private javax.swing.JCheckBox j42;
    private javax.swing.JCheckBox j43;
    private javax.swing.JCheckBox j44;
    private javax.swing.JCheckBox j45;
    private javax.swing.JCheckBox j46;
    private javax.swing.JCheckBox j47;
    private javax.swing.JCheckBox j48;
    private javax.swing.JTextArea jDiagnostico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextArea jProcedimento;
    private javax.swing.JTextArea jPrognostico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jSolicitar;
    // End of variables declaration//GEN-END:variables
}
