/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author rafael
 */
public class TelaPrincipalSecretario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalSecretario
     */
    public TelaPrincipalSecretario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bConsultas = new javax.swing.JButton();
        bCirurgias = new javax.swing.JButton();
        bPacientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bConsultas.setText("Cadastrar Consultas");
        bConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bConsultasMouseClicked(evt);
            }
        });

        bCirurgias.setText("Cadastrar Cirurgias");
        bCirurgias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCirurgiasMouseClicked(evt);
            }
        });

        bPacientes.setText("Cadastrar Pacientes");
        bPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPacientesMouseClicked(evt);
            }
        });

        jLabel1.setText("Secretario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(bConsultas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCirurgias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPacientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConsultas)
                    .addComponent(bCirurgias)
                    .addComponent(bPacientes))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(776, 393));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConsultasMouseClicked
        CadastrarConsulta cadastrarConsulta = new CadastrarConsulta();
        cadastrarConsulta.setVisible(true);
        
    }//GEN-LAST:event_bConsultasMouseClicked

    private void bCirurgiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCirurgiasMouseClicked
        CadastrarCirurgia cadastrarCirurgia = new CadastrarCirurgia();
        cadastrarCirurgia.setVisible(true);
        
    }//GEN-LAST:event_bCirurgiasMouseClicked

    private void bPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPacientesMouseClicked
        CadastrarPaciente cadastrarPaciente = new CadastrarPaciente();
        cadastrarPaciente.setVisible(true);
        
    }//GEN-LAST:event_bPacientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalSecretario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCirurgias;
    private javax.swing.JButton bConsultas;
    private javax.swing.JButton bPacientes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
